### ISSUE TITLE
Implementar a medida `Team Throughput`

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#133]
## História de Usuário
Eu como usuário do MSG 
Desejo **visualizar o valor atual e o histórico da medida ```Team Throughput```**
Para que eu possa **ter um maior catálogo de medidas ao analisar a SQC de um repositório**.

## Critérios de aceite
- [ ] O usuário deve conseguir visualizar o último valor da Team Throughput
- [ ] O usuário deve conseguir visualizar o histórico da medida
- [ ] Os gráficos de linha para a medida devem estar disponíveis
- [ ] O usuário deve ser capaz de recuperar o último valor e o histórico da medida tanto pelo dashboard quanto pela cli

## Tarefas

* [ ] Backend 
  * [ ] Implementar a função que calcula o `Team Throughput` no serviço `core`
  * [ ] Calcular o valor da métrica e salvar no serviço `service`
  * [ ] Disponibilizar a métrica na API
  * [ ] Verificar a métrica aparece automaticamente no dashboard e caso não realizar as ações necessárias para incluir a nova métrica

**Comment by hneri** [comment]
@KiSobral parece-me que essa história está realizando duas ações. Sugiro torná-las independentes.

1a
--
Calcular a medida  Team Throughput

Como Miguel eu 
Desejo visualizar valores calculados da medida Team Throughput
Para que eu observe a taxa vazão das US em um projeto

## Critérios de aceite
- [ ] O usuário deve conseguir visualizar o último valor da Team Throughput
- [ ] O usuário deve conseguir visualizar o histórico da medida em um gráfico de de linha, via dashboard
- [ ] O usuário deve ser capaz de recuperar o último valor e o histórico da medida tanto pelo dashboard quanto pela cli

2a
--
Calcular a medida  Team Throughput

Como Valeria eu 
Desejo calcular o valor da medida Team Throughput
Para eu poder quantificar uma percepção da subcaracterística completude funcional e sua respectiva característica, adequação funcional

## Critérios de aceite
- [ ] Garantir que as métricas são validas e não nulas
- [ ] Garantir que os valores de referência estejam definidos
- [ ] O cálculo deve ser baseado na formula:

<img width="810" alt="Captura de Tela 2022-07-23 às 15 50 04" src="https://user-images.githubusercontent.com/3755938/180619829-50bf5945-ebe9-481e-9452-8b5e31c7ed80.png">


OBS:
IF_7 representa a função de interpretação da medida em7 e iota, a função de interpolação linear da IF_7
