### ISSUE TITLE
Implementar a medida `CI Feedback time`

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#134]
## História de Usuário

Eu como usuário do MSG 
Gostaria de **visualizar o valor atual e o histórico de valores da medida ``CI Feedback time``**
Pois dessa maneira:
  *  eu **poderia conhecer de maneira prática o tempo médio de "resposta" da pipeline de CI do repositório**;
  * me permitiria **compreender como esse tempo de médio de "resposta" está se comportando ao decorrer do tempo, facilitando assim minha análise**;
  * a minha **visão da qualidade do software se torna mais rica**, uma vez que o modelo suporta medidas de diferentes aspectos do software.
  
## Critérios de aceitação

- * Deve ser possível visualizar no dashboard o valor atual da medida `CI Feedback time`
- * Deve ser possível visualizar no dashboard os valores históricos da medida `CI Feedback time`
- * Deve ser possível obter o valor atual dessa medida utilizando o comando da CLI `measuresoftgram get measure <ID_DA_MEDIDA_CRIADA>
- * O valor calculado deve está correto (VALIDAÇÃO DA FORMULA ESCRITA COM O CLIENTE!!)

## Tarefas
* [ ] Geral
  * [ ] Estudar a fundo sobre esta medida
  * [ ] Reconhecer o valor desta medida ao usuário 

* [ ] Backend 
  * [ ] Implementar a função que calcula o `CI feedback time` no serviço `core`
  * [ ] Calcular o valor da métrica e salvar no serviço `service`
  * [ ] Disponibilizar a métrica na API
  * [ ] Verificar a métrica aparece automaticamente no dashboard e caso não realizar as ações necessárias para incluir a nova métrica
    * [ ] Verificar a métrica aparece automaticamente no comando `get measure` da CLI e caso não apareça realizar as modificações necessárias para incluir a nova métrica
