### ISSUE TITLE
Visualizar a nova medida `Issues-type in a timeframe`

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#135]
## História de Usuário

Eu como **usuário do MSG** 
gostaria de **visualizar o valor atual e o histórico da métrica `Issues-type in a timeframe`**
Para que assim [...] [escrever restante da história]

* TODOs:
  * Descobrir o que é essa medida
  * Descobrir qual é o valor dessa medida para o usuário

## Tarefas
* [ ] Backend 
  * [ ] Implementar a função que calcula o `Issues-type in a timeframe` no serviço `core`
  * [ ] Calcular o valor da métrica e salvar no serviço `service`
  * [ ] Disponibilizar a métrica na API
  * [ ] Verificar a métrica aparece automaticamente no dashboard e caso não realizar as ações necessárias para incluir a nova métrica

**Comment by KiSobral** [comment]
Devido às classificações contraditórias em torno de épico. Esta issue será fechada por tempo indeterminado para reorganização do escopo do projeto.
