### ISSUE TITLE
Implementar a medida `Resolved Issues Throughput`

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#136]
Eu como usuário do MSG gostaria de visualizar o valor atual e o histórico da métrica `Resolved Issues Throughput`

## Tarefas

* [ ] Backend 
  * [ ] Implementar a função que calcula o `Resolved Issues Throughput` no serviço `core`
  * [ ] Calcular o valor da métrica e salvar no serviço `service`
  * [ ] Disponibilizar a métrica na API
  * [ ] Verificar a métrica aparece automaticamente no dashboard e caso não realizar as ações necessárias para incluir a nova métrica

**Comment by KiSobral** [comment]
Devido às classificações contraditórias em torno de épico. Esta issue será fechada por tempo indeterminado para reorganização do escopo do projeto.
