### ISSUE TITLE
Visualizar a página de detalhamento de um `repositório`

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#138]
Eu como usuário gostaria de abrir o site do lean inception e visualizar uma tela que me apresenta informações sobre determinado projeto cadastrado.

**Ps**.: O objetivo dessa tarefa é definir o layout da página e a disposição das informações, dos gráficos, e dos elementos textuais. 

Um exemplo dessa tela pode ser visto a seguir:

![image](https://user-images.githubusercontent.com/31013187/179120220-0a09c316-54e5-4925-8b8b-c96f27b8be52.png)

### Tarefas
- [x] #170 Criar e esstruturar o repositório no GitHub do dashboard do MeasureSoftGram 
- [x] Criar sidebaar
- [x] Criar header
- [x] Criar corpo da página organização
- [x] Criar corpo da página de projetos
- [ ] Conectar informations com a api

**Comment by durvalcarvalho** [comment]
@LeoSilvaGomes 
Podemos fechar essa issue?
Quando eu acessei o link não consegui ver a página de detalhamendo do projeto. Qual link tenho que usar?

**Comment by durvalcarvalho** [comment]
![image](https://user-images.githubusercontent.com/31013187/179743689-f1ae0029-1a20-428e-9c69-9e7bf4d84213.png)

https://measuresoftgram-service.herokuapp.com/api/v1/organizations/1/repository/1/

**Comment by durvalcarvalho** [comment]
![image](https://user-images.githubusercontent.com/31013187/179743745-6ac5b804-b711-4bde-9af9-ec0ed942d5b6.png)
