### ISSUE TITLE
Visualizar os valores históricos das `medidas` no dashboard

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#140]
Eu como usuário do MSG gostaria de visualizar o histórico de valores das medidas calculadas.

Uma vez que o MSG possui em sua base de dados diversas métricas coletadas de diversas fontes, e possui implementado as fórmulas que calculam as medidas com base nas métricas, eu gostaria de visualizar via dashboard os valores que as medidas assumiram ao decorrer do tempo.

Uma possível maneira de visualizar essa informação é com base em um gráfico de linha. 
Segue um exemplo de um gráfico de linha:
![image](https://user-images.githubusercontent.com/31013187/178997536-bbb72285-2aee-4798-b60e-b153413b9afc.png)

## Tarefas
* [ ] Backend
  * [x] Definir a interface (estrutura do JSON e endpoint) que será disponibilizada na API e avisar o responsável no frontend, para que assim possa começar o trabalho
  * [ ] Criar uma consulta ao banco de dados que recupere o histórico de uma determinada medida.
  * [ ] Criar uma classe ou função que serialize os dados no formato de JSON
  * [ ] Criar um endpoint e servir os dados
* [ ] Frontend
  * [x] Definir a biblioteca que será usada para gerar o gráfico de linha
  * [x] Criar uma função que manipule os dados fornecidos pela API e transforme no formato exigido pela biblioteca
  * [x] Criar o componente de gráfico de linhas que possa ser estilizado com o nome da medida 
  * [x] Configurar e estilizar o componente com dados falsos
  * [x] Obter os dados da API do backend e utilizá-los no componente

**Comment by durvalcarvalho** [comment]
O endpoint foi mockado e já está disponível na seguinte url
https://measuresoftgram-service.herokuapp.com/api/v1/organizations/1/repository/1/history/measures/

**Comment by durvalcarvalho** [comment]
https://github.com/fga-eps-mds/2022-1-MeasureSoftGram-Doc/issues/139

**Comment by durvalcarvalho** [comment]
https://github.com/fga-eps-mds/2022-1-MeasureSoftGram-Front/pull/16

**Comment by durvalcarvalho** [comment]
Toda o backend necessário para essa issue foi implementado
https://github.com/fga-eps-mds/2022-1-MeasureSoftGram-Service/pull/5
