### ISSUE TITLE
Obter o valor atual de uma ou mais (`medidas` | `medida`) via CLI

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#142]
## História de Usuário
Eu como usuário do MSG 
Desejo obter, por linha de comando, o último valor calculado para uma medida
Para visualizar informações relevantes de um projeto.

## Critérios de aceita
- [ ] Quando o usuário inserir o comando, deve ser mostrado, em terminal, o nome, o último valor calculado e a data de calculo da medida.
- [ ] O usuário não deve depender do serviço de dashboard web para obter a última medida.
- [ ] O usuário deve digitar apenas um comando.
- [ ] O usuário deve informar, por meio de um parâmetro do comando, a organização do projeto.
- [ ] O usuário deve informar, por meio de um parâmetro do comando, o endereço do projeto.
- [ ] O usuário deve informar, por meio de um parâmetro do comando, a medida desejada.
- [ ] O usuário pode, por meio do parâmetro ```--host```, especificar qual o endereço do service que a CLI deverá apontar.

## Tarefas
* [ ] Backend
  * [x]  Definir a interface (estrutura do JSON e endpoint) que será disponibilizada na API e avisar o responsável da CLI e do Frontend, para que assim possa começar o trabalho
  * [x] Modelar a tabela `Medida` e `Métrica` para armazenar os dados calculados.
  * [x] Cadastrar no banco de dados as `Métricas` necessárias para calcular a Medida.
  * [ ] Entender como a requisição deve ser feita para o service `core` para que o resultado do cálculo da medida seja feito.
  * [ ] Salvar o resultado do cálculo no banco de dados, juntamente com a data atual do cálculo.
  * [ ] Criar uma classe ou função que serializa os dados em formato JSON
  * [ ] Criar um endpoint e servir os dados

* [ ] CLI 
  * [ ] Criar um comando que consulta a API do `service`
  * [ ] Criar um parâmetro do comando que retorna somente determinada métrica
  * [ ] Analisar e validar se o formato retornado pela API é aceitável ou é preciso formato o dado em outro formato

## Observação 
Uma vez que o MSG possui em sua base de dados diversas métricas coletadas de diversas fontes, e possui implementado as fórmulas que calculam as medidas com base nas métricas, eu gostaria de obter o valor atual de determinada medida utilizando um comando do CLI.
