### ISSUE TITLE
Visualizar o histórico de valores e o valor atual de uma ou mais subcaracterísticas via dashboard

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#144]
Eu como usuário do MSG gostaria de visualizar o valor atual e o histórico de valores das subcaracterísticas.

Uma vez que o sistema já é capaz de calcular as métricas de uma subcaracterística e também já possui uma pré-configuração implementada, é desejável que seja possível obter o valor de uma subcaracterísticas com base nos pesos e nas métricas definidas. 

## Tarefas
* [x] Backend
  * [x] Modelar a tabela que irá armazenar o histórico de valores calculados das subcaracterísticas
  * [x] Criar uma classe ou função que serializa os dados em formato JSON
  * [x] Criar um endpoint e servir os dados
* [ ]  Frontend
  * [ ] Usar os componentes existentes para apresentar os dados obtidos na API
