### ISSUE TITLE
Visualizar o histórico de valores e o valor atual de uma ou mais características via dashboard

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#146]
Uma vez que já é possível visualizar os valores das subcaracterísticas, gostaria que seja possível obter o valor calculado pelo modelo das características de qualidade do projeto.

## Tarefas
* [ ] Backend
  * [ ] Definir a interface (estrutura do JSON e endpoint) que será disponibilizada na API e avisar o responsável da CLI e do Frontend, para que assim possa começar o trabalho
  * [ ] Modificar a pré-configuração para suportar a seleção de características
  * [ ] Modificar a pré-configuração para a seleção de ao menos uma subcaracterísticas para cada características selecionada
  * [ ] Modificar a pré-configuração para suportar a definição de pesos das subcaracterísticas que foram selecionadas
  * [ ] Entender como a requisição deve ser feita para o service core para que o resultado do cálculo da medida seja feito.
  * [ ] Salvar o resultado do cálculo no banco de dados, juntamente com a data atual do cálculo.
  * [ ] Criar uma classe ou função que serializa os dados em formato JSON
  * [ ] Criar um endpoint e servir os dados
* Frontend
  * [ ] Habilitar o botão da barra lateral para que possa ser visualizado o resultado das características
  * [ ] Configurar e estilizar os componente de visualização existentes com dados falsos
  * [ ] Obter os dados da API do backend e utilizá-los no componente

**Comment by KiSobral** [comment]
Devido às classificações contraditórias em torno de épico. Esta issue será fechada por tempo indeterminado para reorganização do escopo do projeto.
