### ISSUE TITLE
Criar comando na CLI para importar métricas de um ou mais arquivo do SonarQube

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#152]
## História de usuário

Como Miguel,
Gostaria de **utilizar um comando na CLI que importasse para o sistema os vários arquivos gerados pelo SonarQube** que tenho em um diretório do meu computador,
Para eu conseguir **processar múltiplos arquivos** referentes a múltiplas releases.

## Critérios de aceitação

- [x] Deve existir o comando: `measuresoftgram import sonarqube <DIR_NAME>` capaz de especificar o diretório onde os arquivos estão.
- [x] Deve existir o parâmetro `--host` que especifica a URL da instância do serviço `service` onde os JSONs contidos nos arquivos serão enviados; 
  - [x] Caso o parâmetro `--host` não seja especificado deve ser utilizado o valor contido na variável de ambiente `MSG_SERVICE_HOST`;
  - [x] A variável de ambiente `MSG_SERVICE_HOST` inicialmente deve ser específica com o valor `https://measuresoftgram-service.herokuapp.com/`;
- [x] Caso o valor defindo para a URL da instância do serviço host não termine com o caracter `/` ele deve ser adicionado por default;
- [x] Para cada arquivo deve ser realizado ao menos 3 tentativas de envio em cenários de erros de rede;
- [x] Uma vez que esse comando pode demorar alguns segundos, é preciso que exista um logging informando o usuário a ação que está sendo feita no momento. Um exemplo de logging é apresentado [neste link](https://gist.github.com/durvalcarvalho/ab05bae550cf836b9c6228a542e95b60);
- [x] O novo comando deve ter suporte aos (--organization_id, --repository_id) que especificam qual repositório que os dados dos arquivos deve ser enviado;
- [x] Arrumar os testes

## Observação
Um grande valor ao usuário trazido por esta US é justamente a alternativa a criação manual de um script, isto é, não se faz mais necessário ter que criar um script que para cada arquivo enviasse o JSON contido para o endpoint de import de arquivos do SonarQube, e assim, pouparia tempo.

**Comment by hneri** [comment]
Ajuste na escrita da US
--
Eu como Miguel,
Gostaria de utilizar um comando na CLI que importasse para o sistema os vários arquivos gerados pelo SonarQube que tenho em um diretório do meu computador,
Para eu conseguir processar múltiplos arquivos referentes a múltiplas releases.

**Comment by hneri** [comment]
sobre o primeiro critério de aceitação: "Deve existir o comando: measuresoftgram import..." somente o nome do diretório deve ser informado. O sistema deve ler todos os arquivos do diretório. Já existe uma verificação do formato do arquivo gerado pelo sonarqube.
