### ISSUE TITLE
Gerenciar uma conta via dashboard

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#161]
## Descrição
Criar a funcionalidade de Criação/Visualização/Edição/Deleção da conta de um usuário.

## Critérios de Aceitação:
- O usuário deve ser capaz de criar uma conta para acessar o MeasureSoftGram.
- O usuário deve ser capaz de visualizar as informações da sua conta para uma maior transparência dos dados armazenados.
- O usuário deve ser capaz de editar as informações da sua conta de acordo com a sua necessidade.
- O usuário deve ser capaz de deletar a sua conta.
- Todas as ações com a entidade de conta do usuário devem ser feitas por meio de uma interface visual agradável e seguindo o protótipo de alta fidelidade/identidade visual.

## Tarefas Back:
- [ ] Criar uma modelagem dos dados relacionados com a conta de usuário.
- [ ] Criar as tabelas no banco com suas devidas características (not null, unique constraints, triggers, functions e indexes).
- [ ] Criar o endpoint de criação da conta.
- [ ] Criar endpoint de visualização da conta.
- [ ] Criar endpoint de edição da conta.
- [ ] Criar endpoint de deleção da conta.

## Tarefas Front:
- [ ] Criar estrutura da tela de CRUD da conta de acordo com o protótipo de alta fidelidade (HTML/CSS)
- [ ] Criar integração com o Backend nos endpoints do CRUD criados.
- [ ] Criar validação dos campos de edição da conta.

Observação: Issue original escrita por: @lboaventura25 
![image](https://user-images.githubusercontent.com/31013187/179630777-7b44adc7-e006-4d64-b6e7-272744e0549c.png)

**Comment by KiSobral** [comment]
Devido às classificações contraditórias em torno de épico. Esta issue será fechada por tempo indeterminado para reorganização do escopo do projeto.
