### ISSUE TITLE
Obter o histórico de valores de uma ou mais (`medidas` | `métrica`) via CLI

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#190]
## História de Usuário

Como Valéria
Gostaria de **obter o histórico de valores de uma ou mais medidas e suas respectivas métricas** via CLI
Para eu conseguir visualizar **quais medidas compõem e quantificam suas respectivas subcaracterísticas**.

## Critérios de aceitação

- [x] A execução do comando `measuresoftgram get measures --history` deve apresentar o histórico de valores das medidas calculadas do registro mais antigo para o mais novo;
- [x] A execução do comando `measuresoftgram get metrics --history` deve apresentar o histórico de valores das métricas coletadas do registro mais antigo para o mais novo;
- [x] A execução do comando `measuresoftgram get metrics --history --help` deve apresentar a documentação de como utilizar o comando e seus parâmetros;
- [x] Os parâmetros existentes (`--host`, `--organization_id`, `--repository_id`, `--output_format`) do comando `measuresoftgram get` devem continuar funcionando com o novo recurso `--history`;
- [x] Deve ser possível utilizar o comando com um identificador numérico (`measuresoftgram get metrics <INT> history`) para obter o histórico de somente uma (métrica | medida)
- [x] Quando for utilizado o comando sem o identificador numérico, o histórico de (medidas | métricas) devem ser agrupadas, ou seja, os registros de uma mesma (medida | métrica) devem está sem juntos.
- [x] Deve ser possível utilizar o parâmetro `--output_format` com os valores `json` e `tabular`, sendo que a visualização padrão é a visualização tabular.

## Tarefas

- [x] Criar um client para a API do serviço `service` para assim desacoplar o código da requisição do código de apresentação.
- [x] Adicionar o novo argumento `history` no CLI parser do comando `get`.
- [x] Modificar o JSON obtido pela API para apresentar no formato tabulado
- [x] Apresentar os dados no terminal

**Comment by hneri** [comment]
Ajuste na escrita da US:
Como Valéria,
Eu gostaria de obter o histórico de valores de uma ou mais medidas e suas respectivas métricas, via CLI,
Para eu conseguir visualizar quais medidas compõem e quantificam suas respectivas subcaracterísticas.

**Comment by hneri** [comment]
Visualizar somente as medidas e métricas sem a visualizar suas respectivas subcaraterísticas e características, não tem muito significado para o usuário.

**Comment by KiSobral** [comment]
> Visualizar somente as medidas e métricas sem a visualizar suas respectivas subcaraterísticas e características, não tem muito significado para o usuário.

A ideia desta US é servir como base para que, quando implementarmos a visualização das características e subcaracterísticas, tenhamos um alto valor agregado e completo ao usuário que utiliza o MSG via dashboard.

**Comment by durvalcarvalho** [comment]
> Visualizar somente as medidas e métricas sem a visualizar suas respectivas subcaraterísticas e características, não tem muito significado para o usuário.

Concordo contigo, o obtenção somente das `medidas | métricas` não tem muito valor. Porém criamos esse Epico pq uma vez que ele seja implementado o esforço para evoluir para a obtenção do histórico de valores das `subcaraterísticas | características` é mínimo, já que a base de código é a mesma. 

Desse modo, acredito que é interessante mantê-lo na sprint.
