### ISSUE TITLE
Visualizar os cards de valores atuais de uma ou mais medidas ao mesmo tempo via dashboard

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#192]
## História de Usuário

Eu como usuário do MSG
Desejo visualizar os **cards que contém os últimos valores de uma determinada medida**
Para conseguir visualizar **de maneira mais simples e objetiva os últimos valores das medidas** de uma subcaracterística.

## Critérios de aceite
- [x] O usuário deve visualizar um card por medida de cada subcaracterística
- [x] Todas as medidas devem ser disponibilizadas na tela
- [x] As medidas devem ser disponibilizadas a partir da subcaracterística selecionada (todas as medidas de uma determinada subcaracterística)
- [x] O card deve mostrar o nome da medida, o último valor calculado para a medida e a data do cálculo
- [x] O card da medida deve ser clicável (ao clicar no card, não é necessário para a história da implementação das informações que devem ser mostradas após o clique)
- [x] Embora o card seja um componente visual, as informações relativas ao card podem ser acessadas não somente pelo dashboard.

## Tarefas
- [x] Backend
   - [x] Disponibilizar um endpoint que retorna todas as medidas, seus últimos valores calculados e a data de cálculo de cada medida
- [x] Frontend
    - [x] Criação do componente de card
    - [x] Criação da tela que lista todas as medidas de cada subcaracterística
    - [x]  Tornar o card clicável para que, futuramente, sejam exibidos os gráficos de linha da medida

**Comment by hneri** [comment]
Ajuste na escrita:
Como Miguel eu 
Desejo visualizar valores calculados de uma ou mais medidas 
Para eu observar o comportamento de sua respectiva subcaracterística ao longo do tempo

Acrescentar o seguinte critérios de aceite: 
- [ ] O usuário deve conseguir visualizar o histórico das medidas em um gráfico de linha
