### ISSUE TITLE
Definir a meta de um repositório

### ISSUE THREAD

**Issue by KiSobral** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#229]
## Descrição

Como Valéria
Desejo equalizar(balancear) as características de qualidade de um produto de software
Para definir os objetivos de qualidade (meta) planejadas para cada release de um projeto.

## Critérios de aceitação

- [ ] O componente deve mostrar as características de qualidade suportadas pelo MSG, previamente selecionadas (na pré-configuração)
- [ ] O componente deve mostrar as características de qualidade definidas na pré-configuração de um projeto, previamente selecionadas.
- [ ] A parte do componente responsável por balancear as relações entre as características deve utilizar uma escala VAS, de 100 pontos, conforme: [VAS-Scale](https://drive.google.com/file/d/1-gFBHbBMoN9d8K5Ms7ec0HK6iFGcrsJY/view?usp=sharing). Conferir também: [VAS generator](http://www.vasgenerator.net/)
- [ ] As relações entre as características devem obedecer ao definido em: [Haoues et. al](https://drive.google.com/file/d/1uZXPEfXfMnH-GBBO8SDYfpOOzD4ed_DM/view?usp=sharing ) Para os conflitos entre as relações, utilizar o proposto por: [Neri e Travassos](https://drive.google.com/file/d/1HnlvHtpm7FDxgAN1KkMF9sUhfbPK8gpO/view?usp=sharing)
- [ ] O componente visual deve estar posicionada no ponto 50, ou seja, na metade da escala de 100pts, para todas as características, previamente selecionadas.
- [ ] Quando uma determinada característica for movimentada no componente de equalização, as demais características devem ser movimentadas, proporcionalmente, de acordo com suas relações. Assim, se a relação entre A:B = -1 significa que, A e B tem relação inversamente  proporcional.  Se A:B = 1 significa que, A e B tem relação diretamente proporcional. Se A:B = 0 significa que, não há  relação entre A e B.
- [ ] Metas com valores não válidos não devem ser aceito pelo `service`.

## Observação
Este requisito engloba a interação com o equalizador

- [ ] O dashboard deve enviar para o service a sequência de modificações feitas pelo usuário no componente do equalizador, ou seja, invés de enviar o resultado final deve ser enviado o delta de quanto foi modificado pelo usuário. 

Exemplo:

Se o usuário realizar essa sequência modificações

**PS.:** Nessa imagem as setas azuis são modificações feitas pelo usuário e as laranjas são a reação da ação do usuário. O frontend tem que ficar de olho nas ações feitas pelo usuário e mandá-las para o backend.

![image](https://user-images.githubusercontent.com/31013187/185514528-d2919e93-cc6c-472b-97cb-0dc122e77d40.png)

O dashboard deve enviar o seguinte JSON:

```json
{
    "release_name": "v1.0.0",
    "start_at": "2022-08-19",
    "end_at": "2022-09-19",
    "changes": [
        {
            "characteristic_key": "functional_suitability",
            "delta": 10
        },
        {
            "characteristic_key": "performance_efficiency",
            "delta": -10
        },
        {
            "characteristic_key": "security",
            "delta": 40
        }
    ]
}
```

**Comment by heronsousa** [comment]
@hneri O protótipo para o equalizador com as mudanças solicitadas. https://www.figma.com/file/SUDrpsX09BJr6hLivq5Mte/MeasureSoftwareGram?node-id=251%3A3665

**Comment by hneri** [comment]
Ajuste na escrita da história:
Como Valéria
Desejo equalizar as características de qualidade de um produto de software
Para definir os objetivos de qualidade (meta) planejadas para cada release de um projeto

**Comment by hneri** [comment]
> @hneri O protótipo para o equalizador com as mudanças solicitadas. https://www.figma.com/file/SUDrpsX09BJr6hLivq5Mte/MeasureSoftwareGram?node-id=251%3A3665

Algumas observações sobre o protótipo:
- não aparece qual organização-projeto estão selecionados
- não fica clara qual é a release do projeto que está sendo planejada
- Substituir a pegunta "Deseja utilizar essas configurações para as releases futuras?" por Deseja utilizar essa meta para releases futuras?
@heronsousa

**Comment by hneri** [comment]
Redefinição dos Critérios de aceitação:

- [ ] O componente deve mostrar as características de qualidade suportadas pelo MSG, previamente selecionadas.
- [ ] O componente deve mostrar as características de qualidade definidas na pré-configuração de um projeto, previamente selecionadas.
- [ ] A parte do componente responsável por balancear as relações entre as características deve utilizar uma escala VAS, de 100 pontos, conforme: [VAS-Scale](https://drive.google.com/file/d/1-gFBHbBMoN9d8K5Ms7ec0HK6iFGcrsJY/view?usp=sharing)
Conferir também: [VAS generator](http://www.vasgenerator.net/)
- [ ] As relações entre as características devem obedecer ao definido em: [Haoues et. al](https://drive.google.com/file/d/1uZXPEfXfMnH-GBBO8SDYfpOOzD4ed_DM/view?usp=sharing ) Para os conflitos entre as relações, utilizar o proposto por: [Neri e Travassos](https://drive.google.com/file/d/1HnlvHtpm7FDxgAN1KkMF9sUhfbPK8gpO/view?usp=sharing)
- [ ] O componente visual deve estar posicionada no ponto 50, ou seja, na metade da escala de 100pts, para todas as características, previamente selecionadas.
- [ ] Quando uma determinada característica for movimentada no componente de equalização, as demais características devem ser movimentadas, proporcionalmente, de acordo com suas relações. Assim, se a relação entre A:B = -1 significa que, A e B tem relação inversamente  proporcional.  Se A:B = 1 significa que, A e B tem relação diretamente proporcional. Se A:B = 0 significa que, não há  relação entre A e B.
- [ ] No fluxo criação de uma [meta](https://www.figma.com/file/SUDrpsX09BJr6hLivq5Mte/MeasureSoftwareGram?node-id=341%3A2166) deve haver uma opção para selecionar os projetos via texto. Enquanto o nome do projeto for sendo digitado a seleção deverá acontecer de forma dinâmica.

OBS: Esse mecanismo de balanceamento entre as relações é uma proposta inicial, ainda sem expressar a intensidade das relações entre as características.
@heronsousa @DanilloGS @durvalcarvalho @danieldagerom @KiSobral

**Comment by durvalcarvalho** [comment]
@hneri 

> - [ ] No fluxo criação de uma meta deve haver uma opção para selecionar os projetos via texto. Enquanto o nome do projeto for sendo digitado a seleção deverá acontecer de forma dinâmica.

Sobre esse critério de aceite, é desejável que uma meta seja utilizada com vários repositórios?

Após conversa interna com os membros da equipe chegamos na conclusão que a relação entre meta e repositório é de n para 1, ou seja, uma meta é somente de um repositório, mas um repositório pode ter várias metas, sendo somente a mais recente e meta vigente.

Você pode confirmar isso para gente?

**Comment by hneri** [comment]
Uma meta está associada a um ou mais releases de um projeto, independente da quantidade de repositórios. Uma vez definida uma meta de um release, esta deve ser utilizada em todos os repositórios de um determinado projeto.
@durvalcarvalho @DanilloGS @heronsousa @KiSobral

**Comment by durvalcarvalho** [comment]
Esse critério de aceitação deve ir para a issue da tela do projetos

- [ ] No fluxo criação de uma [meta](https://www.figma.com/file/SUDrpsX09BJr6hLivq5Mte/MeasureSoftwareGram?node-id=341%3A2166) deve haver uma opção para selecionar os projetos via texto. Enquanto o nome do projeto for sendo digitado a seleção deverá acontecer de forma dinâmica.
