### ISSUE TITLE
Criar uma meta via API

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#267]
## Descrição

Eu como [Miguel](https://fga-eps-mds.github.io/2022-1-MeasureSoftGram-Doc/#/documentos/visao_do_produto?id=personas), gostaria de criar uma meta de um produto via API, pois dessa maneira eu poderia integrar o sistema do MeasureSoftGram com o sistema já existente que utilizam na organização que trabalho, permitindo assim que os usuários desse sistema atual consigam utilizar o MeasureSoftGram sem precisar abrir outro site. 

## Critérios de Aceitação:

- [ ] Não deve ser possível criar metas com características inexistentes
- [ ] Não deve ser possível criar metas com características que não estão definidas na pré-configuração vigente
- [ ] Após a criação de uma meta deve ser retornado todas as características da pré-configuração com os pesos definidos de acordo com a regra de equalização
- [ ] Deve ser possível obter a meta vigente de um produto

**Comment by durvalcarvalho** [comment]
## Como testar a API com base nos critérios de aceitação

### Não deve ser possível criar metas com características inexistentes

Faça uma requisição para o endpoint `/api/v1/organizations/ID1/products/ID2/create/goal/` com uma característica inexistente, onde ID1 é o identificador de uma organização e ID2 é o identificador do produto recém criado.

**Exemplo:**
```bash
curl --location --request POST 'https://measuresoftgram-service.herokuapp.com/api/v1/organizations/4/products/5/create/goal/' \
--header 'Content-Type: application/json' \
--data-raw '{
    "release_name": "invalid-goal",
    "start_at": "2023-01-31",
    "end_at": "2023-04-30",
    "changes": [
        { "characteristic_key": "fake-characteristic", "delta": 10 }
    ]
}'
```

<br><br><br><br>

### Não deve ser possível criar metas com características que não estão definidas na pré-configuração vigente

Faça uma requisição para o endpoint `/api/v1/organizations/ID1/products/ID2/create/goal/` com uma característica não definida na pré-configuração, onde ID1 é o identificador de uma organização e ID2 é o identificador do produto recém criado.

**Exemplo:**
```bash
curl --location --request POST 'https://measuresoftgram-service.herokuapp.com/api/v1/organizations/4/products/5/create/goal/' \
--header 'Content-Type: application/json' \
--data-raw '{
    "release_name": "invalid-goal",
    "start_at": "2023-01-31",
    "end_at": "2023-04-30",
    "changes": [
        { "characteristic_key": "security", "delta": 10 }
    ]
}'
```

<br><br><br><br>

### Após a criação de uma meta deve ser retornado todas as características da pré-configuração com os pesos definidos de acordo com a regra de equalização

Faça uma requisição para o endpoint `/api/v1/organizations/ID1/products/ID2/create/goal/`e depois verifique se a response enviada está com todos as características definidas na pré-configuração com os pesos de acordo com a regra de equalização, onde ID1 é o identificador de uma organização e ID2 é o identificador do produto recém criado.

**Exemplo:**
```bash
curl --location --request POST 'https://measuresoftgram-service.herokuapp.com/api/v1/organizations/4/products/5/create/goal/' \
--header 'Content-Type: application/json' \
--data-raw '{
    "release_name": "invalid-goal",
    "start_at": "2023-01-31",
    "end_at": "2023-04-30",
    "changes": [
        { "characteristic_key": "reliability", "delta": 10 },
        { "characteristic_key": "reliability", "delta": 3 },
        { "characteristic_key": "maintainability", "delta": -50 }
    ]
}' | jq
```

<br><br><br><br>

### Deve ser possível obter a meta vigente de um produto

Faça uma requisição para o endpoint `/api/v1/organizations/ID1/products/ID2/current/goal/`, onde ID1 é o identificador de uma organização e ID2 é o identificador do produto recém criado.

**Exemplo:**
```bash
curl --location --request GET 'https://measuresoftgram-service.herokuapp.com/api/v1/organizations/4/products/5/current/goal/'
```
