### ISSUE TITLE
Exibir histórico da SQC na tela de repositório

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#275]
## História de Usuário

**TODO:** Melhorar essa história de Usuário

Como Valéria
Desejo visualizar o histórico da SQC de todos os repositórios que compõem o produto
Para conseguir visualizar de forma analítica as informações agregadas do meu produto.

## Critérios de aceitação
**TODO:** Validar esses critérios de aceitação

- [ ] Deve plotar histórico do SQC como gráfico de linha
- [ ] Deve plotar histórico do SQC como gráfico tabular
- [ ] Deve ser possível visualizar o histórico do SQC no grafico do histórico de caracteristicas
- [ ] Ao colocar o ponteiro do mouse em cima de um ponto da linha, deve forncer detalhes do ponto (Todos os valores do ponto que virão do Back-end)
- [ ] Deve ser possível realizar download do gráfico
- [ ] Deve pegar valores do histórico das metas cadastradas de cada release realizada
- [ ] Deve pegar valores calculados, a partir do equalizador e configurações, em cada release 
- [ ] Valores resgatados do back devem estar sincronizados por release
- [ ] Deve plotar históricos como gráfico de linha

## Protótipo

**TODO:** Adicionar o link correto além do screenshot

![image.png](https://images.zenhubusercontent.com/5bbe0ba8c245624f0b833529/3c095d09-f2ee-4666-aba3-5f701251c37d)

**Comment by hneri** [comment]
**Ajuste:**  ajuste na escrita da história 

Como Valéria
Desejo visualizar o histórico do indicador SQC e das Características de um repositório
Para assim conseguir visualizar de forma analítica as informações agregadas de um repositório

**Validação Critérios Aceitação:** 
- [ ] Deve ser possível informar o intervalo de datas do período a ser plotado no gráfico
- [ ] Deve plotar histórico do SQC como gráfico de linha, ao longo do tempo (intervalo informado). A linha do SQC deve ter uma espessura maior do que as linhas das características.
- [ ] Ao selecionar uma característica no menu, deve ser plotado do indicador agregado da característica
- [ ] Deve ser exibida uma legenda identificando as características
- [ ] Ao colocar o ponteiro do mouse em cima de um ponto da linha, deve fornecer detalhes do ponto (nome característica, data e valor)

**OBS:**	
- Exibir o nome do produto do repositório observado(selecionado)
- Esse não é um critério de aceitação do ponto de vista do usuário, mas uma observação sobre a implementação: [Valores resgatados do back devem estar sincronizados por release]

@DanilloGS @durvalcarvalho
